---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2023/3/2 15:29
---


local Bag = class("Bag")

function Bag:ctor(owner)
    self.owner = owner
    self.items = {}
end

function Bag:count()
    print("当前物品数量："..#self.items)
    for name,n in pairs(self.items) do
        print(name,n)
    end
end

function Bag:put(name,n)
    --if #self.space==0 then
    --    print("背包已满")
    --    return
    --end
    if self.items[name]~=nil then
        self.items[name] = self.items[name]+n
    else
        self.items[name] = n
    end
end


return Bag