---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/19 15:43
---

--父类
local Player = require("test_object_oriented.Player")
local Student = require("test_object_oriented.Student")


-- 继承
local Employee = {}
Employee.parents = {Player,Student}
local function search(parents,k)    -- 多重继承的 __index搜索策略
    for i=1,#parents do
        local res = parents[i][k]
        if res then return res end
    end
    print(k.."无对应属性")
    return nil
end
setmetatable(Employee,
        {__index = function(t,k)
            return search(t.parents,k)
        end}
)
Employee.company = "公司名称"
Employee.__index = Employee


-- 构造方法
function Employee:new(info)
    local object = {}
    self:init(info,object)
    setmetatable(object,self)
    return object
end


-- 新方法
function Employee:employeeIntroduce()
    local sex
    local game
    if self.ismale then
        sex = "男"
    else
        sex = "女"
    end
    if type(self.game)=="table" then
        print("有多种游戏")
        game = table.concat(self.game,"、")
    else
        game = self.game
    end
    local info = {
        "我是"..self.name,
        "性别为"..sex,
        "今年"..self.age.."岁",
        "喜欢的游戏是"..game,
        "毕业于"..self.school,
        "目前在"..self.company.."工作"
    }
    print(table.concat(info,"，"))
end


return Employee