---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/15 16:20
---

require("structure")

local Person = {name="无名",ismale=true,age=-1}
Person.__index = Person

-- 对象构造方法
function Person.new(name,ismale,age)
    local object = {}
    setmetatable(object,Person)
    -- 在元表中找到父类的ctor进行属性赋值
    object:ctor(name,ismale,age)
    return object
end

-- 属性赋值
function Person:ctor(name,ismale,age)
    if name~=nil then
        self.name = name
    end
    if ismale~=nil then
        self.ismale = ismale
    end
    if age~=nil then
        self.age = age
    end
end

function Person:get(k,v)
    return self[k]
end

function Person:set(k,v)
    self[k] = v
end

return Person