---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/15 16:20
---

require("structure")

local Person = class("Person")

function Person:ctor(name,ismale,age)
    if name~=nil then
        self.name = name
    end
    if ismale~=nil then
        self.ismale = ismale
    end
    if age~=nil then
        self.age = age
    end
end

function Person:get(k,v)
    return self[k]
end

function Person:set(k,v)
    self[k] = v
end

return Person