---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/18 15:21
---

local Person = require("test_object_oriented.Person")

-- 继承
local Player = Person.new()
Player.__index = Player

-- 重写构造方法
function Player.new(name,ismale,age,game)
    local object = {}
    setmetatable(object,Player)
    return object
end

function Player:ctor(info)
    for k,v in pairs(info) do
        self.k = v
    end
end

function Player:print()
    for k,v in pairs(self) do
        if type(v)~="table" then
            print(k,v)
        end
    end
end