---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/19 15:23
---

local Person = require("test_object_oriented.Person")

-- 继承
local Student = Person:new()
Student.school = "毕业院校"
Student.__index = Student

-- 重写构造函数