---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14563.
--- DateTime: 2022/5/6 23:09
---

-- 针对只有一个成员的简单类和其对象
function newObj(value)
    -- value被保存在返回函数的closure中
    return function(action,v)
        if action=="get" then return value
        elseif action=="set" then value=v
        else error("无效操作")
        end
    end
end

a = newObj(10)
b = newObj(20)
print("a = " .. a("get"))
print("b = " .. b("get"))
a("set",a("get")+30)
print("a+30 = " .. a("get"))
