---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/15 16:54
---

require("structure")
local Person = require("test_object_oriented.Person")

local dsh = Person.new("dsh",true,22)
print(dsh:get("age"))