---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/21 18:01
---

a = "123456"
print(string.sub(a,3,4))
b = "\t".."\t"..a
x = 10
print("\t"..x,"xxx","Hello")