---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/21 17:58
---

require("structure")

------------------------------- 定义测试 -------------------------------
structure.Func_type("table定义测试",true)

t0 = {}
t_string = {"de","da","c"}
t_int = {2,3,6,5,1,4}
t_hash = {[2]=199, ["我"]="狄仕豪",["你"]="什么",["他"]="哈哈哈",game = "dota"}
t_hash_2 = {name="dsh", age=23,["我"]="狄仕豪"}

function table_show(t)
    for i,v in pairs(t) do
        print(i,v)
    end
end
table_show(t_hash)

print(t_hash.game)

structure.Func_type("table定义测试",false)
------------------------------- 定义测试 -------------------------------


------------------------------- 输出嵌套table -------------------------------
structure.Func_type("输出嵌套table",true)

function printTable(t,level)
    local prefix = "- "
    for i=1,level do
        prefix = "\t"..prefix
    end
    for i,data in pairs(t) do
        local type = type(data)
        if type=="function" then
            print(prefix..i,"这是一个函数")
        elseif type==nil then
            print(prefix..i,"nil")
        elseif type=="table" then
            print(prefix..i)
            printTable(data,level+1)
        else
            print(prefix..i,data)
        end
    end
end

local test = {
    name = "dsh",
    games = {"dota","MHR","Re2"},
    gender = true,
    account = {
        { "skyelfxxx@126.com","code1" },
        { "1456@qq.com","code2"}
    }
}

printTable(test,1)

structure.Func_type("输出嵌套table",false)
------------------------------- 输出嵌套table -------------------------------

























