---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/8 10:14
--- 输出UI控件信息

local utils = require("cardSango.utils")

local data = require("cardSango.data_UI")
--
--for i=1,9 do
--    print(i, data.Content.Content.ObjectData.Children[i].Name)
--end
utils:printTable(data.Content.Content.ObjectData.Children,1,"Name")