---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/8 10:12
--- 辅助测试的相关方法

Utils = {}

--@t 输出对象
--@level 当前嵌套级别
function Utils:printTable(t,level,target)
    local prefix = ""
    local islocked = false      -- 输出锁定
    prefix = "<"..level..">："
    for i=1,level do
        prefix = "\t"..prefix
    end
    for i,data in pairs(t) do
        -- 若非目标字段，锁定输出
        if target~=nil then
            if tostring(i)~=target then
                islocked = true
            else
                islocked = false
            end
        end
        local type = type(data)
        if type=="function" and not islocked then
            print(prefix,i,data,"("..type..")")
        elseif type=="nil" and not islocked then
            print(prefix,i,"nil")
        elseif type=="table" then
            if islocked then
                self:printTable(data,level+1,target)
            else
                print(prefix,i,"("..type..")")
                self:printTable(data,level+1,target)
            end
        elseif not islocked then
            print(prefix,i,data,"("..type..")")
        end
    end
end

return Utils