---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/8/27 11:49
---
testFile = {}

_M.info = {}
info.x = 10

function _M.getInfo()
    return info
end

return testFile