---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/25 14:10
---

require("structure")

structure.Func_type("协同程序基础测试",true)

x=1
y=1
z=0

function add(a,b)
    z = a+b
end

co_1 = coroutine.create(add)
coroutine.resume(co_1,x,y)
print(z)    -- 2

structure.Func_type("协同程序基础测试",false)