---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/25 14:24
---

require("structure")

structure.Func_type("resume-yield测试",true)

msgs = {"第一次","什么","你好","嘿嘿嘿","求求了"}

function receive()
    local status,value = coroutine.resume(boss())
end

function send(x)
    coroutine.yield(x)
end

function boss()
    for i=1,5 do
        send(msgs[i])
    end
end

function me()
    for i=1,5 do
        local msg = receive()
        print(i,msg .. "\n")
    end
end

co_1 = coroutine(me())
co_2 = coroutine(boss())
coroutine.resume(co_1)

structure.Func_type("resume-yield测试",false)