---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/26 14:30
---


local count = 0

function Entry(...)
    --count = count+1
    local table = ...
    print(table[#table])
end

dofile("G:/MyProgrames/Lua/Test_Lua/data.lua")
