---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/26 14:22
---

file = io.open("test.txt","r+")

for line in io.lines(file) do
    print(line)
end