---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/25 14:55
---

require("structure")

structure.Func_type("马尔科夫链算法",true)

-- the more we try the more we do
--statetab = {
--    ["\n \n"] = {"the"},
--    ["\n the"] = {"more"},
--    ["the more"] = {"we","we"},
--    ["more we"] = {"try","do"},
--    ["we try"] = {"the"},
--    ["we do"] = {"\n"},
--    ["try the"] = {"more"}
--}

local statetab = {}

-- 生成迭代器
function allwords()
    local line = io.read()
    local pos = 1
    return function()
        while line do
            local s,e = string.find(line,"%w+",pos)
            if s then
                pos = e+1
                return string.sub(line,s,e)
            else
                line = io.read()
                pos = 1
            end
        end
        return nil
    end
end

function prefix(w1,w2)
    return w1 .. " " .. w2
end

-- 插入新的前缀-后缀关系
function insert(index,value)
    local list = statetab[index]
    if list==nil then statetab[index]={value}
    else list[#list+1] = value
    end
end

local N = 2
local MAXGEN = 10000
local NWORD = "\n"

-- 构建table
local w1,w2 = NWORD,NWORD
for w in allwords() do
    insert(prefix(w1,w2),w)
    w1 = w2; w2 = w;
end
insert(prefix(w1,w2),NWORD)

-- 生成文本
w1 = NWORD; w2 = NWORD
for i=1,MAXGEN do
    local list = statetab[prefix(w1,w2)]
    -- 从列表中选择随机项
    local r = math.random(#list)
    local nextword = list[r]
    if nextword==NWORD then return end
    io.write(nextword," ")
    w1,w2 = w2,nextword
end





structure.Func_type("马尔科夫链算法",true)