---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/21 14:28
---

print("Hello World")
local input = io.read("*n")
print(input)
print(type(input))

t = {name="dsh", ["age"]=23}
print(t.age)