---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/26 17:17
---

function serialize(o)
    if type(o)=="number" then io.write(o)
    elseif type(o)=="string" then
        io.write(string.format("%q",o))
    elseif type(o)=="table" then
        io.write("\n")
        for k,v in pairs(o) do
            io.write("  ",k," = ")
            serialize(v)
            io.write("\n")
        end
        io.write("\n")
    else error("无法串行化此类型：" .. type(o))
    end
end