---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/24 15:10
---

structure = {}

-- 常量
structure.constant = 1

function structure.Func_type(name,mod)
    if mod then print("\n\n//------------------- " .. name .. "-------------------//\n")
    else print("\n//------------------- " .. name .. "-------------------//\n\n") end
end

-- 私有函数
local function show_constant()
    print(structure.constant)
end

return structure