---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/4 15:16
---


local useful = require("useful")

local x = "age"
local info = {}
info.age = 10
print(info[x])









