---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/4 15:16
---


local useful = require("useful")

--local function test(x,y)
--    if y==nil then
--        print("未传入参数y")
--    end
--    local data = x or {}
--    print(data,y)
--end
--

local function isNil(data)
    if data==nil then
        print(true)
    else
        print(false)
    end
end

--local data = {}
--local buff = {4,8,9}
--table.insert(data,2,{3,4})
--table.insert(data,4,{1,2,3,6})
--table.insert(data,3,buff)
--data.xx = {}
--buff = {}

local function printParams(...)
    local params = {...}
    for i=1,#params do
        print(params[i])
    end
end

printParams(10,"你好")

local datas = {}
for i=1,5 do
    local enum = {index=i,data=i*10}
    table.insert(datas,enum)
    datas[#datas].data = i*10+1
    print(enum.data)
end
--useful:printTable(datas)





