---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/4 15:16
---


local useful = require("useful")

--local function test(x,y)
--    if y==nil then
--        print("未传入参数y")
--    end
--    local data = x or {}
--    print(data,y)
--end
--

local function isNil(data)
    if data==nil then
        print(true)
    else
        print(false)
    end
end

local data = {}
local buff = {4,8,9}
table.insert(data,2,{3,4})
table.insert(data,4,{1,2,3,6})
table.insert(data,3,buff)
data.xx = {}
buff = {}

for type,data in pairs(data) do
    print(type)
    for _,v in ipairs(data) do
        print("\t"..v)
    end
end


print(data)


