---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/21 15:10
---

print(type(nil  ))
print(type(true))

print(type(100))
print("1"*2)
print(1 .. 123)
print(1 .. "12")

print(type("Hello World"))
print(type(print))


table_test = {1,2,5,6,"什么东西"}
print(#table_test)


function test_select(...)
    result = select(3,...)
    print(select(3,...))
    print(type(result))
end

test_select(1,2,3,4,5,6)


print("\n")

a = {"我","是","你"}
for i,v in pairs(a) do
    print(v)
end














