---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/7/4 11:26
---

local useful = {}

useful.testData = {}
useful.testData.x = 10
function useful:getTestData()
    return self.testData
end

--@t table
--@level 当前嵌套级别
function useful:printTable(t,level,target)
    local prefix = ""
    local islocked = false      -- 输出锁定
    if level==nil then
        level = 1
    end
    prefix = "<"..level..">："
    for i=1,level do
        prefix = "\t"..prefix
    end
    for i,data in pairs(t) do
        -- 若非目标字段，锁定输出
        if target~=nil and data~=target then
            islocked = true
        end
        local type = type(data)
        if type=="function" and not islocked then
            print(prefix,i,data,"("..type..")")
        elseif type=="nil" and not islocked then
            print(prefix,i,"nil")
        elseif type=="table" then
            if islocked then
                self:printTable(data,level+1,nil)
            else
                print(prefix,i,"("..type..")")
                self:printTable(data,level+1,nil)
            end
        elseif not islocked then
            print(prefix,i,data,"("..type..")")
        end
    end
end

return useful