---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14563.
--- DateTime: 2022/4/29 20:05
---

--a = 10
--setfenv(1,{g=_G})
--g.print(a)      --> nil
--g.print(g.a)    --> 10


------------------------------- 使用继承组装新环境 -------------------------------

a = 1
local new_env = {}  -- 新环境
setmetatable(new_env,{__index = _G})
setfenv(1,new_env)
print("a = " .. a)
a,b = 10,20
print("新环境的变量：" .. a .. "，" ..b)
print("原先环境的变量a = " .. _G.a)






