---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14563.
--- DateTime: 2022/5/14 19:51
---

require("structure")
Func_type = structure.Func_type
local name

name = "基础"
------------------------------- 基础 -------------------------------
Func_type(name,true)

print(string.format("format实例：\n\tpi = %.2f",math.pi))

Func_type(name,false)
------------------------------- 基础 -------------------------------


name = "匹配模式"
------------------------------- 匹配模式 -------------------------------
Func_type(name,true)

local str_1 = "What's your name?"
local i,j = string.find(str_1,"name")
print("“name”的位置："..i..", "..j)

local str_2 = "Today is 2022/5/15"
local date = string.match(str_2,"%d+/%d+/%d+")
print("字符串中的日期：" .. date)

local str_3 = str_2 .. ", tomorrow is 2022/5/16"
local new_str3 = string.gsub(str_3,"2022","二零二二")
print("替换后的str_3：" .. new_str3)

local str_4 = "苹果的英文是apple，刀塔原名DotA，SC是星际争霸的简称"
for w in string.gmatch(str_4,"%a+") do
    print(w)
end

-- 模拟require寻找模块的策略
function search(modname,path)
    -- 将 . 替换成 /
    modname = string.gsub(modname,"%.","/")
    for c in string.gmatch(path,"[^;]+") do
        -- 用模块名替换路径用分号分开的各部分中的?
        local fname = string.gsub(c,"?",modname)
        local f = io.open(fname)
        if f then
            f:close()
            return fname
        end
    end
    return nil      -- 未找到
end

Func_type(name,false)
------------------------------- 匹配模式 -------------------------------


name = "捕获"
------------------------------- 捕获 -------------------------------
Func_type(name,true)

local str_5 = "name = dsh, 出生日期：1999/08/14"
local name = string.match(str_5,"%a+%s*=%s*(%a+)")
local year,month,day = string.match(str_5,"(%d+)/(%d+)/(%d+)")
print(name..", "..year..", "..month..", "..day)

local new_str5 = string.gsub(str_5,"(%d+)/(%d+)/(%d+)","%1-%2-%3")
print(new_str5)

Func_type(name,false)
------------------------------- 捕获 -------------------------------


name = "捕获"
------------------------------- 捕获 -------------------------------
Func_type(name,true)



Func_type(name,false)
------------------------------- 捕获 -------------------------------


name = "捕获"
------------------------------- 捕获 -------------------------------
Func_type(name,true)



Func_type(name,false)
------------------------------- 捕获 -------------------------------