---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14563.
--- DateTime: 2022/5/9 20:52
---

require("structure")
local Func_type = structure.Func_type


------------------------------- 三角函数 -------------------------------
Func_type("三角函数",true)

local sin,asin,cos = math.sin,math.asin,math.cos
local deg,rad = math.deg,math.rad
local exp,log,log10 = math.exp,math.log,math.log10
local floor,ceil = math.floor,math.ceil
local max,min = math.max,math.min


beta_deg = 45
beta_rad = rad(beta_deg)
print("sin(45°) = ".. sin(beta_rad))

Func_type("三角函数",false)
------------------------------- 三角函数 -------------------------------


------------------------------- 对数、指数 -------------------------------
Func_type("对数、指数",true)

print("e**2 = " .. exp(2))

Func_type("对数、指数",false)
------------------------------- 对数、指数 -------------------------------


------------------------------- 最值 -------------------------------
Func_type("最值",true)

print("max{1,2,6,5,3} = " .. max(1,2,6,5,3))

Func_type("最值",false)
------------------------------- 最值 -------------------------------


------------------------------- 取整 -------------------------------
Func_type("取整",true)

print("向下取整：-0.58 = "..floor(-0.58))
print("向上取整：2.39 = "..ceil(2.39))

Func_type("取整",false)
------------------------------- 取整 -------------------------------

