---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14563.
--- DateTime: 2022/5/9 20:27
--- 弱引用与table默认值
---

-- 弱引用表，存储目标table的字段统一默认值
local defaults = {}
setmetatable(defaults,{__mode="k"})
local mt = {__index = function(t) return defaults[t] end}

function setDefault_1(t,d)
    defaults[t] = d     -- 表-默认值
    -- 指定当表中没有目标字段时，从defaults中获取默认值
    setmetatable(t,mt)
end


-- 存储：默认值-带搜索策略的元表
local metas = {}
setmetatable(meta,{__mode="v"})
function setDefault_2(t,d)
    local mt = metas[d]
    if mt==nil then
        mt = {__index = function() return d end}
        metas[d] = mt
    end
    setmetatable(t,mt)
end
