---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 14563.
--- DateTime: 2022/4/30 10:26
--- 复数模块
---


module("complex_2",package.seeall)

i = {r=0, i=1}

-- 复数构造
function new(r,i)
    local new_c = {r=r, i=i}
    local mt = {__tostring = function(c)
        return r.. ", " ..i.." *i"
    end
    }
    setmetatable(new_c,mt)
    return new_c
end

-- 复数相加
function add(c1,c2)
    return new(c1.r+c2.r, c1.i+c2.i)
end
