---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/8/17 10:51
---

module("dataFile",package.seeall)

local name = "dsh"

function getName()
    return name
end