---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/24 11:45
---


------------------------------- closure测试 -------------------------------

function create_count(ini)
    local i=ini     -- 被装入返回的函数的closure中
    return function(step)
        if step==nil then step=1 end
        i = i+step
        return i
    end
end

--x、y各创建了一个closure
x = create_count(2)     -- 该closure的upvalue=2
y = create_count(0)     -- 该closure的upvalue=0

print(x(1))     -- 3
print(x(10))    -- 13
print(y())            -- 1


------------------------------- closure测试 -------------------------------
