---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/25 11:30
---

require("structure")

------------------------------- loadstring -------------------------------
structure.Func_type("loadstring测试",true)

i = 0
local add_i = loadstring("i=i+1")
add_i()
add_i()
print(i)

structure.Func_type("loadstring测试",false)
------------------------------- loadstring -------------------------------


------------------------------- err -------------------------------
structure.Func_type("错误与其处理测试",true)

local x_n = 10
local x_table = {5,4,3,2,6}

function test(a)
    a = x_table
    if type(a)~="table" then error("传入的不是table") end
    print(a[i])
end

local status,err = pcall(test)
if not status then
    print(err)
end

structure.Func_type("错误与其处理测试",false)
------------------------------- err -------------------------------













