---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Administrator.
--- DateTime: 2022/4/22 10:47
---


------------------------------- 非全局函数测试 -------------------------------

Lib = { add = function(x,y) return x+y end}
Lib.sub = function(x,y) return x-y end
function Lib.multi(x,y) return x*y end
print(Lib.add(1,10),Lib.sub(5,1),Lib.multi(3,3))

--local function fib(n)
--    if n<3 then return 1
--        else return fib(n-1)+fib(n-2)
--    end
--end
--
--print(fib(3),fib(4),fib(5))

print("\n\n\n")

------------------------------- 非全局函数测试 -------------------------------








